- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 0
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0
    - !type:DepartmentTimeRequirement
      department: Security
      time: 0
    - !type:OverallPlaytimeRequirement
      time: 0
  weight: 20
  startingGear: HoPGear
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  # I mean they'll give themselves the rest of the access levels *anyways*.

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
